config/routes.rb
Rails.application.routes.draw do

  root                'static_pages#home'
  get    'help'    => 'static_pages#help'
  get    'about'   => 'static_pages#about'
  get    'contact' => 'static_pages#contact'
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  get    'notifications/show_all', to: 'notifications#show_all', as: 'notifications'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
<<<<<<< HEAD
  get 	'test'	=>	'notifications#test'
=======
>>>>>>> 8764b3c22486d84ce9368cb5a5266bcb6bf665e6
  resources :users do
    member do
      get :following, :followers
    end
    resources :conversations do
      resources :messages
    end
  end
  resources :conversations do
    resources :messages
  end

  get     '/messages/new', :to => 'messages#new', :as => :messages_path

  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
  resources :notifications,       only: [:create, :show, :destroy]  #Création, affichage et suppression des notifications
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
<<<<<<< HEAD
    Site fait avec l'aide de Ruby on Rails</a>
  </small>
  <nav>
    <ul>
			<% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
				 <i class="fa fa-cog fa-2x"></i><b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Compte", current_user %></li>
				  <li><%= link_to "Configuration", edit_user_path(current_user) %></li>
            </ul>
			 </li>
			<% end %>

        <li><%= link_to "Aide",   help_path %></li>
      <li><%= link_to "A propos",   about_path %></li>
      <li><%= link_to "Nous joindre ", contact_path %></li>
    </ul>
  </nav>
</footer>
=======
    The <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    by <a href="http://www.michaelhartl.com/">Michael Hartl</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>
>>>>>>> 8764b3c22486d84ce9368cb5a5266bcb6bf665e6

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
<<<<<<< HEAD
    <nav>
      <ul class="nav navbar-nav navbar-right" >
        <li class="<%= active_class(root_path)%>" >
				 <%= link_to root_path do %>
    				<span class="fa-stack fa-lg">
						<i class="fa fa-home fa-stack-2x " style="color:White;"></i>
					</span>
  				  <% end %>
		 </li>
        <% if logged_in? %>
          <li class="<%= active_class(users_path)%>" > 	
				  <%= link_to users_path do %>
    				<span class="fa-stack fa-lg">
						<i class="fa fa-users fa-stack-2x " style="color:#007AA3;"></i>
					</span>
  				  <% end %>
			</li>

          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
				 <i class="fa fa-bell fa-3x" style="color:green;"></i><b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
				<li><%= link_to "Notifications ("+current_user.notifications.count.to_s+")", notifications_path if (current_user.notifications.count>0)%></li>

            <li><%= link_to "Notifications", notifications_path if(current_user.notifications.count==0)%></li>
            </ul>
			 </li>
          <li>
			  <%= link_to logout_path, method: :delete do %>
    		   <span class="fa-stack fa-lg">
  				 <i class="fa fa-power-off fa-stack-2x " style="color:red;"></i>
				</span>
  			  <% end %>
           </li>
           </ul>

        <% else %>
          <li>
				<%= link_to login_path do %>
    			 <span class="fa-stack fa-lg">
  					<i class="fa fa-power-off fa-stack-2x " style="color:green;"></i>
				 </span>
  				<% end %>
			</li>
=======
    <%= link_to "sample app", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",   root_path %></li>
        <li><%= link_to "Help",   help_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Users", users_path %></li>
            <li><%= link_to "Notifications ("+current_user.notifications.count.to_s+")", notifications_path if(current_user.notifications.count>0)%></li>
            <li><%= link_to "Notifications", notifications_path if(current_user.notifications.count==0)%></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
>>>>>>> 8764b3c22486d84ce9368cb5a5266bcb6bf665e6
        <% end %>
      </ul>
    </nav>
  </div>
<<<<<<< HEAD
</header>


=======
</header>
>>>>>>> 8764b3c22486d84ce9368cb5a5266bcb6bf665e6

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <meta content='<%= "" %>' name='user-id'/>
    <%= stylesheet_link_tag    'application', media: 'all', 
                                              'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<<<<<<< HEAD
	 
	 <!-- Dependencies -->
<!-- 	 <link rel="stylesheet" href="bower_components/bootstrap/dist/css/bootstrap.min.css">
	 <script src="bower_components/angularjs/angular.js"></script>

	 
	 <link rel="stylesheet" href="bower_components/angular-bootstrap-simple-chat/src/css/style.css">
	 <script src="bower_components/angular-bootstrap-simple-chat/src/scripts/index.js"></script>

	 <link rel="stylesheet" href="bower_components/angular-bootstrap-simple-chat/src/css/themes.css">
 -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
	 <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css" rel="stylesheet">
	 <%= csrf_meta_tags %>
=======
    <%= csrf_meta_tags %>
>>>>>>> 8764b3c22486d84ce9368cb5a5266bcb6bf665e6
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>

      <%= render 'layouts/footer' %>
<<<<<<< HEAD

=======
>>>>>>> 8764b3c22486d84ce9368cb5a5266bcb6bf665e6
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>